package com.example.rewardservice.user.dto;

import com.example.rewardservice.user.domain.User;
import lombok.*;
import org.springframework.security.core.GrantedAuthority;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.UUID;

@Getter
@Setter
@ToString
public class UserDTO {
    private UUID id;
    private String userId;
    private String userPassword;
    private String userName;
    private long totalPoint;
    private LocalDateTime lastUpdateDate;

    public UserDTO(UUID id, String userId, String userPassword, String userName, long totalPoint, LocalDateTime lastUpdateDate) {
        this.id = id;
        this.userId = userId;
        this.userPassword = userPassword;
        this.userName = userName;
        this.totalPoint = totalPoint;
        this.lastUpdateDate = lastUpdateDate;
    }

    // Empty constructor required for frameworks like Spring to instantiate the class
    public UserDTO() {
    }

    // If you need to construct a UserDTO from a User entity and authorities
    public UserDTO(User user, Collection<GrantedAuthority> authorities) {
        this.id = user.getId();
        this.userId = user.getUserId();
        this.userPassword = user.getUserPassword();
        this.userName = user.getUserName();
        this.totalPoint = user.getTotalPoint();
        this.lastUpdateDate = user.getLastUpdateDate();
    }

    // Getters and setters can be generated by lombok, if preferred
}
