name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mydb

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2

    - name: Build with Gradle Wrapper
      env:
        AWSRDS: ${{ secrets.AWSRDS }}
        AWSS3: ${{ secrets.AWSS3 }}
        JWTKEY: ${{ secrets.JWTKEY }}
      run: |
        chmod +x ./gradlew
        ./gradlew build --warning-mode all

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Init with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.8

    - name: Generate and submit dependency graph
      env:
        AWSRDS: ${{ secrets.AWSRDS }}
        AWSS3: ${{ secrets.AWSS3 }}
        JWTKEY: ${{ secrets.JWTKEY }}
      run: ./gradlew dependencies --warning-mode all
